version: '3.9'

services:
  python-flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python-flask-prototype
    depends_on:
      - postgres
    ports:
      - '${FLASK_RUN_PORT}:${FLASK_RUN_PORT}'
    environment:
      FLASK_ENV: '${FLASK_ENV}'
      FLASK_APP: '${FLASK_APP}'
      FLASK_RUN_HOST: '${FLASK_RUN_HOST}'
      FLASK_RUN_PORT: '${FLASK_RUN_PORT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DATABASE_URL: '${DATABASE_URL}'
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db-prototype
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
